language: php
php:
  - "7.1"
  - "7.0"
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"
env:
  - DOKUWIKI=master
  - DOKUWIKI=stable
before_install:
  - wget https://raw.github.com/splitbrain/dokuwiki-travis/master/travis.sh
  - npm install
install: sh travis.sh
script:
  - cd _test && phpunit --stderr --group plugin_tablelayout
  - cd ../lib/plugins/tablelayout && grunt
